#!/bin/bash
# setup.sh for profile: daaam-cosmos
# Holds one GPU allocation open. Use `bjob connect <jobid>` from IDE
# terminals to choose Cosmos, a prepared DAAAM shell, plain shell, or GPU status.

export PROJECT="${PROJECT:-/proj/rpl-soro/users/$USER}"
export HOI_FPS="${HOI_FPS:-4.0}"
export COSMOS_GPU_MEMORY_UTILIZATION="${COSMOS_GPU_MEMORY_UTILIZATION:-0.75}"
export COSMOS_URL_FILE="${COSMOS_URL_FILE:-$PROJECT/.cosmos_url.${SLURM_JOB_ID:-manual}}"
export DAAAM_AUTO_BATCH_START="${DAAAM_AUTO_BATCH_START:-1}"
export DAAAM_AUTO_BATCH_END="${DAAAM_AUTO_BATCH_END:-7}"
export DAAAM_AUTO_LAUNCH_READY_PATTERN="${DAAAM_AUTO_LAUNCH_READY_PATTERN:-Waiting for CameraInfo on topic}"
export DAAAM_AUTO_READY_FALLBACK_SECONDS="${DAAAM_AUTO_READY_FALLBACK_SECONDS:-480}"
export DAAAM_AUTO_COSMOS_MODELS_WAIT_SECONDS="${DAAAM_AUTO_COSMOS_MODELS_WAIT_SECONDS:-1800}"
export DAAAM_AUTO_BAG_DELAY_SECONDS="${DAAAM_AUTO_BAG_DELAY_SECONDS:-0}"
export DAAAM_AUTO_BAG_START_PAUSED="${DAAAM_AUTO_BAG_START_PAUSED:-0}"
export DAAAM_AUTO_COSMOS_WAIT_SECONDS="${DAAAM_AUTO_COSMOS_WAIT_SECONDS:-1800}"
export DAAAM_AUTO_RUN_ID="${DAAAM_AUTO_RUN_ID:-${SLURM_JOB_ID:-manual}-$(date +%Y%m%d_%H%M%S)}"
export DAAAM_AUTO_STATE_DIR="${DAAAM_AUTO_STATE_DIR:-$PROJECT/.cache/daaam-cosmos-auto/$DAAAM_AUTO_RUN_ID}"

mkdir -p "$PROJECT/.bjob" "$PROJECT/.cache" "$DAAAM_AUTO_STATE_DIR/logs"
ENV_FILE="$PROJECT/.bjob/daaam-cosmos-${SLURM_JOB_ID:-manual}.env"
cat > "$ENV_FILE" <<EOF
export PROJECT="$PROJECT"
export HOI_FPS="$HOI_FPS"
export COSMOS_GPU_MEMORY_UTILIZATION="$COSMOS_GPU_MEMORY_UTILIZATION"
export COSMOS_URL_FILE="$COSMOS_URL_FILE"
export DAAAM_AUTO_BATCH_START="$DAAAM_AUTO_BATCH_START"
export DAAAM_AUTO_BATCH_END="$DAAAM_AUTO_BATCH_END"
export DAAAM_AUTO_LAUNCH_READY_PATTERN="$DAAAM_AUTO_LAUNCH_READY_PATTERN"
export DAAAM_AUTO_READY_FALLBACK_SECONDS="$DAAAM_AUTO_READY_FALLBACK_SECONDS"
export DAAAM_AUTO_COSMOS_MODELS_WAIT_SECONDS="$DAAAM_AUTO_COSMOS_MODELS_WAIT_SECONDS"
export DAAAM_AUTO_BAG_DELAY_SECONDS="$DAAAM_AUTO_BAG_DELAY_SECONDS"
export DAAAM_AUTO_BAG_START_PAUSED="$DAAAM_AUTO_BAG_START_PAUSED"
export DAAAM_AUTO_COSMOS_WAIT_SECONDS="$DAAAM_AUTO_COSMOS_WAIT_SECONDS"
export DAAAM_AUTO_RUN_ID="$DAAAM_AUTO_RUN_ID"
export DAAAM_AUTO_STATE_DIR="$DAAAM_AUTO_STATE_DIR"
EOF

NODE="${SLURMD_NODENAME:-$(hostname -s)}"

echo "DAAAM + Cosmos allocation is ready on node: $NODE"
echo "Job ID: ${SLURM_JOB_ID:-unknown}"
echo "Environment: $ENV_FILE"
echo ""
echo "Open each IDE terminal with:"
echo "  bjob connect ${SLURM_JOB_ID:-<jobid>}"
echo ""
echo "Then choose: cosmos, daaam, shell, gpu, logs, auto-launch, auto-bag, or auto."
echo "Manual daaam prepares ROS env, HOI_FPS, and COSMOS_URL; set BATCH_NAME manually."
echo ""
echo "Automated batches: batch_${DAAAM_AUTO_BATCH_START}..batch_${DAAAM_AUTO_BATCH_END}"
echo "Bag readiness: waits for launch log pattern: $DAAAM_AUTO_LAUNCH_READY_PATTERN"
echo "Readiness fallback: ${DAAAM_AUTO_READY_FALLBACK_SECONDS}s; Cosmos /v1/models wait: ${DAAAM_AUTO_COSMOS_MODELS_WAIT_SECONDS}s."
echo "Post-ready delay: ${DAAAM_AUTO_BAG_DELAY_SECONDS}s."
echo "Set DAAAM_AUTO_BAG_START_PAUSED=1 to keep bag playback paused."
echo "Automation state/logs: $DAAAM_AUTO_STATE_DIR"
echo ""
echo "For one-terminal automated mode, run:"
echo "  bjob connect ${SLURM_JOB_ID:-<jobid>} auto"
echo ""
echo "The separate roles still exist for debugging:"
echo "  bjob connect ${SLURM_JOB_ID:-<jobid>} cosmos"
echo "  bjob connect ${SLURM_JOB_ID:-<jobid>} auto-launch"
echo "  bjob connect ${SLURM_JOB_ID:-<jobid>} auto-bag"
echo ""
echo "Keep this allocation shell open. Exiting it ends the node allocation."
